name: Prevent Direct Push to Main

on:
  push:
    branches:
      - main

jobs:
  prevent-direct-push:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if push directly to main
        run: |
          echo "Direct push to main is not allowed. Please create a pull request."
          exit 1
